workflows:
  ios-firebase:
    name: iOS Firebase Distribution
    max_build_duration: 120  
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - FIREBASE_IOS # Group to associate the environment with
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"   
        FIREBASE_IOS_APP_ID: $FIREBASE_IOS_APP_ID # Replace with your Firebase iOS App ID
        BUNDLE_ID: "com.codemagicFirebaseAppDistribution.io" # Replace with your app's bundle ID
        FIREBASE_IOS_JSON: $FIREBASE_IOS_JSON # Base64-encoded Firebase key
        FIREBASE_AUTH_TOKEN: $FIREBASE_AUTH_TOKEN # Firebase token for publishing
    scripts:
      - name: Check environment variables
        script: echo $FIREBASE_IOS_ALIAS
      - name: Set up Firebase Distribution Key
        script: echo $FIREBASE_IOS_JSON | base64 --decode > /ios/firebase_key.json
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Analyze Flutter code
        script: |
          flutter analyze
      - name: Run Flutter tests
        script: |
          flutter test
        ignore_failure: true # Optional: Ignore test failures
      - name: Build iOS IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      firebase:
        firebase_token: $FIREBASE_TOKEN # Add the Firebase token securely
        ios:
            app_id: $FIREBASE_IOS_APP_ID
            groups:
             - iosTesters
      email:
        recipients:
          - huber.marina@gmail.com
        notify:
           success: true 
           failure: false 
