workflows:
  ios-firebase:
    name: iOS Firebase Distribution
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.codemagicFirebaseAppDistribution.io
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - FIREBASE_IOS
        - MANUAL_CODE_SIGN
        - APPSTORE_CRED
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"   
        BUNDLE_ID: "com.codemagicFirebaseAppDistribution.io"
        APP_STORE_ID: 6740295135 
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: set up provisioning profiles
        script: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          PROFILE_PATH="$(mktemp "$PROFILES_HOME"/$(uuidgen).mobileprovision)"
          echo ${CM_PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"
          echo "Saved provisioning profile $PROFILE_PATH"
      - name: Add signing certificate to keychain
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get      
      - name: Flutter build ipa and automatic versioning # agvtool new-version -all $(($BUILD_NUMBER)) responsible for increasing the version number
        script: |
          cd ios
          # Update the version number using agvtool
          agvtool new-version -all $(($BUILD_NUMBER))

          # Navigate back to the project root directory
          cd ..

          # Retrieve the latest build number from TestFlight and increment it
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID")
          NEW_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))

          # Build the Flutter iOS app
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
      - name: Load Firebase configuration plist # By using base64 you load a JSON file or a plist into a string with no spaces, easier to assign to variables in scripts.
        script: | 
          set -e 
          echo $FIREBASE_SECURE | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:              
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        ios: 
          app_id: 1-790432405327-ios-8683d3839010be88f0173a
          groups:
            - iosTesters
      email:
        recipients:
          - huber.marina@gmail.com
        notify:
           success: false 
           failure: false
      app_store_connect:   # https://docs.codemagic.io/publishing-yaml/distribution              
            api_key: $APP_STORE_CONNECT_PRIVATE_KEY         # Contents of the API key, can also reference environment variable such as $APP_STORE_CONNECT_PRIVATE_KEY
            key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER       # Alphanumeric value that identifies the API key, can also reference environment variable such as $APP_STORE_CONNECT_KEY_IDENTIFIER
            issuer_id: $APP_STORE_CONNECT_ISSUER_ID         # Alphanumeric value that identifies who created the API key, can also reference environment variable such a
            submit_to_testflight: false
            submit_to_app_store: false      
