workflows:
  ios-firebase:
    name: iOS Firebase Distribution
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - FIREBASE_IOS
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"   
        BUNDLE_ID: "com.codemagicFirebaseAppDistribution.io"
        APP_STORE_ID: 6740295135 
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.codemagicFirebaseAppDistribution.io
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Flutter analyze
        script: |
          cd . && flutter analyze
        ignore_failure: true          
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist
      - name: Load Firebase configuration
        script: | 
          set -e 
          echo $FIREBASE_IOS_KEY > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist  
      - name: Read release notes
        script: |
          echo "Reading release notes from release_notes.txt"
          RELEASE_NOTES=$(cat release_notes.txt | tr '\n' ' ')  # Convert newlines to spaces
          echo "Release notes: $RELEASE_NOTES"
          echo "$RELEASE_NOTES" > $CM_BUILD_DIR/release_notes.txt  # Save to a temporary file if needed
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      firebase:
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        ios:
          app_id: app-1-790432405327-ios-8683d3839010be88f0173a
          groups:
            - iosTesters
      email:
        recipients:
          - huber.marina@gmail.com
          - nihal@nevercode.io
        notify:
           success: false 
           failure: false 
